import "./globals.css";
import { Inter } from "next/font/google";
import ContextProvider from "@contexts/UserAuthContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PCR - Product Concept Request",
  description: "Generated by Cy-Click",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className} style={{ fontFamily: "LINESeedSans" }}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
